<#macro navbar>
    <div id="navBar">
        <span id="navIcon">Un-llama-ted Adoptions</span>
        <a href="/">Home</a>
        <a href="/new-animal">Submit A New Animal</a>
        <a href="/static/about.html">About</a>
    </div>
    <div id="navBuffer"></div>
</#macro>
<#macro headContents>
    <link rel="stylesheet" href="/static/index.css">
    <meta property="og:title" content="Un-llama-ted Adoptions">
    <meta property="og:image" content="llama1.jpg">
    <meta property="og:description" content="Adopt llamas in need of homes here. Building a community of llama caretakers.">
    <meta property="og:type" content="website">
</#macro>